Lab1-3
t1mtg/Web-5sem pull request #1
Opened 2022-12-05 11:35 UTC by t1mtg

2022-12-05 13:26 UTC, BakasaRus requested changes
По первой лабе нужно всё же показать все теги, которые просят в условии (полужирный, курсив, подчёркивания, зачёркивания и т.д.). Можно для этого сделать отдельную страничку в стиле "О нас"

По второй надо добавить красную строку, расстояние между буквами/словами, курсив (через CSS)

2022-12-05 13:26 UTC, BakasaRus commented on index.html
> +                </ul>
Внутри списка должны быть пункты списка (`<li/>`), внутри которых уже то, что тебе нужно

2022-12-05 13:26 UTC, BakasaRus commented on css/index.css
> +    font-size: 28px;
В чём лучше задавать размер шрифта и прочие типографские штуки?

2022-12-05 13:26 UTC, BakasaRus commented on css/index.css
> +    font-family: 'Times New Roman', Times, serif;
Лучше подтянуть гуглошрифт

2022-12-12 10:41 UTC, t1mtg commented on index.html
> +                </ul>
fixed

2022-12-12 10:41 UTC, t1mtg commented on css/index.css
> +    font-size: 28px;
em rem

2022-12-12 10:41 UTC, t1mtg commented on css/index.css
> +    font-family: 'Times New Roman', Times, serif;
fixed

2022-12-12 14:08 UTC, BakasaRus requested changes
1. Кнопка в таблице не должна ехать при её прокрутке
2. Таблицы вроде бы просили сверстать на гридах

2022-12-19 10:05 UTC, merged